// Затравочные позиции (насекомые для кормления ежей), подмешиваются в справочник
// при самом первом запуске приложения. См. "Позиции корма — сводка.md" в хэндоффе
// дизайна за расшифровкой источников и допущений (проценты — в сухом веществе,
// вес — оценка). caloriesPerGram = 0 у части позиций означает "не найдено в
// источнике" — их нужно дозаполнить вручную перед реальным использованием.
const SEED_POSITIONS = [
  { id: 'p_cricket_domesticus', name: 'Сверчок домовый (Acheta domesticus)', unitWeight: 0.6, caloriesPerGram: 0, proteinPercent: 62.5, fatPercent: 20, fiberPercent: 0, chitinPercent: 12.5, note: '«Золотой стандарт» для ежей: хорошее соотношение Ca:P, умеренная жирность. Хитин полезен для перистальтики и профилактики зубного камня. Влажность живого сверчка ~70-75%, % — в сухом веществе. Вес — оценка.' },
  { id: 'p_cricket_bimaculatus', name: 'Сверчок двупятнистый (Gryllus bimaculatus)', unitWeight: 1, caloriesPerGram: 0, proteinPercent: 57.5, fatPercent: 27.5, fiberPercent: 0, chitinPercent: 11, note: 'Крупный и жирнее домового — осторожно ежам с ожирением/печенью. Хитин у взрослых жёстче; подросткам лучше давать нимф. % в сухом веществе, вес — оценка.' },
  { id: 'p_cricket_banana', name: 'Банановый сверчок (Gryllus assimilis)', unitWeight: 0.6, caloriesPerGram: 0, proteinPercent: 52.5, fatPercent: 16.5, fiberPercent: 0, chitinPercent: 16.5, note: 'Мягкие покровы, хорош для водного баланса и реабилитации/линьки игл, но менее питателен по белку. % в сухом веществе, вес — оценка.' },
  { id: 'p_roach_marbled', name: 'Таракан мраморный (Nauphoeta cinerea)', unitWeight: 0.7, caloriesPerGram: 0, proteinPercent: 62.5, fatPercent: 30, fiberPercent: 0, chitinPercent: 13.5, note: 'Плотный хитин — «ершик» для ЖКТ, но высокий жир: риск набора висцерального жира у малоподвижных ежей. Может вызывать запор у ежат/пожилых при избытке. % в сухом веществе, вес — оценка.' },
  { id: 'p_roach_turkmen', name: 'Таракан туркменский (Shelfordella lateralis)', unitWeight: 0.6, caloriesPerGram: 0, proteinPercent: 57.5, fatPercent: 22, fiberPercent: 0, chitinPercent: 11, note: 'Мягкий хитин, умеренная жирность, больше влаги — близок к идеальному ежедневному корму, в т.ч. для ежей, неохотно пьющих воду. % в сухом веществе, вес — оценка.' },
  { id: 'p_bsf_larva', name: 'Личинка чёрной львинки (Hermetia illucens)', unitWeight: 0.15, caloriesPerGram: 0, proteinPercent: 40, fatPercent: 32.5, fiberPercent: 0, chitinPercent: 8.5, note: 'Суперфуд: соотношение Ca:P близко к идеальному 2:1–3:1, не требует дообваливания в кальции. Лауриновая кислота полезна для микрофлоры. Хорош для кормящих самок и молодняка. % в сухом веществе, вес — оценка.' },
  { id: 'p_mealworm', name: 'Мучной хрущак / Тенебрио (Tenebrio molitor)', unitWeight: 0.15, caloriesPerGram: 0, proteinPercent: 47.5, fatPercent: 35, fiberPercent: 0, chitinPercent: 17.5, note: 'Дешёвый, но Ca:P до 1:10–1:14 — риск деминерализации при частом кормлении. Жёсткий хитин грубоват для ежат. Лакомство, не более 10% рациона; лучше только полинявшие (белые). % в сухом веществе, вес — оценка.' },
  { id: 'p_zoophobas', name: 'Зофобас (Zophobas morio)', unitWeight: 1, caloriesPerGram: 0, proteinPercent: 42.5, fatPercent: 42.5, fiberPercent: 0, chitinPercent: 12.5, note: '«Жирбомба»: Ca:P около 1:20, жир до 40-45%. Главный враг стройной печени ежа — давать крайне редко. % в сухом веществе, вес — оценка.' }
];
